# Run from the repo root
Output ./docs/img/demo.gif

Set FontSize 16
Set FontFamily "GeistMono Nerd Font Mono"
Set Theme "Catppuccin Macchiato"
Set WindowBar Colorful
Set Padding 10
Set Height 1200
Set Width 1200
Set Margin 40
Set MarginFill "#7983FF"
Set BorderRadius 10
Set TypingSpeed 100ms

Type "go test -v ./render -run TestVisualDiff" Sleep 500ms  Enter

Sleep 8s

Type "clear" Sleep 500ms Enter

Sleep 1s
